import { setPublicCors } from './_lib/cors.js'
import { authorizeRestaurantAccess, authorizeRestaurantRole, authorizeSuperadmin, ALL_ROLES, MANAGEMENT_ROLES } from './_lib/authz.js'
import { vercelWrapper } from './_lib/security-middleware.js'
import { rateLimit, acquireLock, releaseLock, getClientIp, resolveClientIp, send429, send503Protection } from '../src/lib/upstash.server.js'
import {
  deleteOldNeonOrders,
  getNeonOrdersPaginated,
  getNeonOrderRestaurantId,
} from '../src/db/neon-orders.js'
import { createOrderAtomic } from '../src/services/orderCreationService.js'
import { applyOrderStatusTransition } from '../src/services/orderStatusService.js'
import {
  generateRequestId,
  safeError,
  badInput,
  unauthorized,
  forbidden,
  notFound,
  conflict,
  internalError,
  rejectUnknownFields,
  validateUuid,
  validateString,
  validateEnum,
  validateIdempotencyKey,
  defineValidation,
  validateRequest,
  parsePagination,
} from './_lib/validate.js'

const ALLOWED_CREATE_FIELDS = ['restaurant_id', 'items', 'table_number', 'table', 'customer_name', 'customerName', 'customer_phone', 'phone', 'customer_location', 'location', 'notes']

// ── /api/orders — Order Operations Handler (Neon-only) ───────────────────────
//
// GET  ?restaurantId=<id>    → list orders for restaurant [ALL_ROLES membership]
// POST (no action)          body: { restaurant_id, items, ... } → create order (public — customer flow)
// POST ?action=updateStatus body: { orderId, status } [MANAGEMENT_ROLES membership]
// POST ?action=autoCleanup  body: { confirmedDeleteHours?, rejectedDeleteMinutes? } [superadmin]
//
// Authorization is ALWAYS enforced — no environment-variable bypass.
// Order creation is server-authoritative: id, status, prices, totals, and
// timestamps are generated by createOrderAtomic, never trusted from the client.

// ── Shared validation definitions ────────────────────────────────────────────
const vQueryRestaurantId = defineValidation('query', { restaurantId: { type: 'uuid', required: true } })
const vBodyCreateOrder = defineValidation('body', {
  restaurant_id: { type: 'string', required: true },
  items: { type: 'array', required: true, minItems: 1 },
})
const vBodyUpdateStatus = defineValidation('body', {
  orderId: { type: 'uuid', required: true },
  status: { type: 'string', required: true },
})

export default vercelWrapper(async function handler(req, res) {
  setPublicCors(res)
  if (req.method === 'OPTIONS') return res.status(200).end()

  const requestId = generateRequestId()

  // ── GET: list orders for a restaurant — requires restaurant membership ──────
  if (req.method === 'GET') {
    let restaurantId
    try {
      const v = validateRequest(req, vQueryRestaurantId)
      restaurantId = v.query.restaurantId
    } catch (e) {
      return badInput(res, 'restaurantId is required', requestId)
    }

    const auth = await authorizeRestaurantRole(req, res, restaurantId, ALL_ROLES)
    if (!auth.ok) return

    try {
      const pagination = parsePagination(req.query)
      const result = await getNeonOrdersPaginated(restaurantId, pagination)
      return res.status(200).json(result)
    } catch (err) {
      console.error('[orders GET] Error:', err.message)
      return internalError(res, requestId)
    }
  }

  if (req.method !== 'POST') return safeError(res, 405, 'Method not allowed', requestId)

  const action = req.query.action

  // ── POST (no action): create order — public customer flow ────────────────────
  if (!action) {
    const body = req.body
    // Validate idempotency key header
    const idempotencyKey = req.headers['idempotency-key']
    try { validateIdempotencyKey(req.headers['idempotency-key']) } catch (e) {
      return badInput(res, 'Idempotency-Key header is required (min 16 characters).', requestId)
    }
    // Validate body fields
    try {
      validateRequest(req, vBodyCreateOrder)
    } catch (e) {
      return badInput(res, 'restaurant_id and a non-empty items array are required', requestId)
    }
    try {
      rejectUnknownFields(body, ALLOWED_CREATE_FIELDS)
      const order = await createOrderAtomic({
        restaurantId: body.restaurant_id,
        tableNumber: body.table_number ?? body.table ?? null,
        customerName: body.customer_name ?? body.customerName ?? null,
        customerPhone: body.customer_phone ?? body.phone ?? null,
        customerLocation: body.customer_location ?? body.location ?? null,
        items: body.items,
        notes: body.notes ?? null,
        idempotencyKey,
      })
      return res.status(201).json(order)
    } catch (err) {
      console.error('[orders POST] Error:', err.message)
      if (err.code === 'IDEMPOTENCY_KEY_REQUIRED') return badInput(res, err.message, requestId)
      if (err.code === 'IDEMPOTENCY_CONFLICT') return conflict(res, err.message, requestId)
      if (err.code === 'VALIDATION') return badInput(res, err.message, requestId)
      if (err.code === 'INVALID_ITEM' || err.code === 'INVALID_OPTION' || err.code === 'INVALID_TABLE') {
        return safeError(res, 422, err.message, requestId)
      }
      if (err.code === 'DUPLICATE') return conflict(res, err.message, requestId)
      return internalError(res, requestId)
    }
  }

  try {
    // ── POST updateStatus — requires MANAGEMENT_ROLES membership ────────────────
    if (action === 'updateStatus') {
      let orderId, status
      try {
        const v = validateRequest(req, vBodyUpdateStatus)
        orderId = v.body.orderId
        status = v.body.status
      } catch (e) {
        return badInput(res, 'orderId and status required', requestId)
      }
      rejectUnknownFields(req.body, ['orderId', 'status', 'restaurantId'])

      const resolvedRestaurantId = await getNeonOrderRestaurantId(orderId)
      if (!resolvedRestaurantId) return notFound(res, 'Order not found', requestId)

      const auth = await authorizeRestaurantRole(req, res, resolvedRestaurantId, MANAGEMENT_ROLES)
      if (!auth.ok) return

      const ipResult = resolveClientIp(req)
      if (ipResult.state !== 'resolved') return send503Protection(res)
      const ip = ipResult.ip
      const rl = await rateLimit(`rl:order-status:ip:${ip}`, 60, 60)
      if (!rl.available) return send503Protection(res)
      if (!rl.allowed) return send429(res, 'Too many order status updates.')
      const lockKey = `lock:order-status:${orderId}`
      const lock = await acquireLock(lockKey, 5)
      if (!lock.available) return send503Protection(res)
      if (!lock.acquired) return conflict(res, 'Status update already in progress.', requestId)
      try {
        const updatedRow = await applyOrderStatusTransition(orderId, status, {
          actorUserId: auth.access.userId,
          actorRole: auth.access.role,
          requestId,
          route: req.path || req.url,
        })
        return res.json({ success: true, orderId, status, restaurant_id: updatedRow.restaurant_id, requestId })
      } catch (transitionErr) {
        if (transitionErr.code === 'TERMINAL' || transitionErr.code === 'INVALID_TRANSITION') {
          return conflict(res, transitionErr.message, requestId)
        }
        if (transitionErr.code === 'INVALID_STATUS') {
          return safeError(res, 422, transitionErr.message, requestId)
        }
        if (transitionErr.code === 'NOT_FOUND') {
          return notFound(res, transitionErr.message, requestId)
        }
        throw transitionErr
      } finally { await releaseLock(lockKey, lock.token) }
    }

    // ── POST autoCleanup — superadmin only ───────────────────────────────────
    if (action === 'autoCleanup') {
      const auth = await authorizeSuperadmin(req, res)
      if (!auth.ok) return

      const { confirmedDeleteHours = 12, rejectedDeleteMinutes = 10 } = req.body || {}
      rejectUnknownFields(req.body || {}, ['confirmedDeleteHours', 'rejectedDeleteMinutes'])
      const now = Date.now()
      const deletedCount = await deleteOldNeonOrders(
        new Date(now - confirmedDeleteHours * 3600000).toISOString(),
        new Date(now - rejectedDeleteMinutes * 60000).toISOString()
      )
      return res.json({ success: true, deletedCount, requestId })
    }

    return badInput(res, `Unknown action: ${action}`, requestId)
  } catch (err) {
    console.error(`[orders][${action}] Error:`, err.message)
    return internalError(res, requestId)
  }
})
