import { setPublicCors } from './_lib/cors.js'
import { checkRestaurantAccess, requireSuperadmin, ALL_ROLES, MANAGEMENT_ROLES } from './_lib/authz.js'
import { rateLimit, acquireLock, releaseLock, getClientIp, send429 } from '../src/lib/upstash.server.js'
import {
  deleteOldNeonOrders,
  getNeonOrders,
  getNeonOrderRestaurantId,
} from '../src/db/neon-orders.js'
import { createOrderAtomic } from '../src/services/orderCreationService.js'
import { applyOrderStatusTransition } from '../src/services/orderStatusService.js'

// ── /api/orders — Order Operations Handler (Neon-only) ───────────────────────
//
// GET  ?restaurantId=<id>    → list orders for restaurant [ALL_ROLES membership]
// POST (no action)          body: { restaurant_id, items, ... } → create order (public — customer flow)
// POST ?action=updateStatus body: { orderId, status } [MANAGEMENT_ROLES membership]
// POST ?action=autoCleanup  body: { confirmedDeleteHours?, rejectedDeleteMinutes? } [superadmin]
//
// Authorization is ALWAYS enforced — no environment-variable bypass.
// Order creation is server-authoritative: id, status, prices, totals, and
// timestamps are generated by createOrderAtomic, never trusted from the client.

export default async function handler(req, res) {
  setPublicCors(res)
  if (req.method === 'OPTIONS') return res.status(200).end()

  // ── GET: list orders for a restaurant — requires restaurant membership ────────
  if (req.method === 'GET') {
    const { restaurantId } = req.query
    if (!restaurantId) return res.status(400).json({ error: 'restaurantId is required' })

    const access = await checkRestaurantAccess(req, restaurantId)
    if (access.error === 'Not authenticated') return res.status(401).json({ error: 'Not authenticated' })
    if (!access.allowed) return res.status(403).json({ error: 'Access denied' })
    if (!access.isSuperadmin && !ALL_ROLES.includes(access.role)) {
      return res.status(403).json({ error: 'Access denied' })
    }

    try {
      const rows = await getNeonOrders(restaurantId)
      return res.status(200).json(rows)
    } catch (err) {
      console.error('[orders GET] Error:', err.message)
      return res.status(500).json({ error: err.message })
    }
  }

  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const action = req.query.action

  // ── POST (no action): create order — public customer flow ─────────────────────
  if (!action) {
    const body = req.body
    const idempotencyKey = req.headers['idempotency-key']
    if (!idempotencyKey || typeof idempotencyKey !== 'string' || idempotencyKey.length < 16) {
      return res.status(400).json({ error: 'Idempotency-Key header is required (min 16 characters).' })
    }
    if (!body?.restaurant_id || !Array.isArray(body?.items) || body.items.length === 0) {
      return res.status(400).json({ error: 'restaurant_id and a non-empty items array are required' })
    }
    try {
      const order = await createOrderAtomic({
        restaurantId: body.restaurant_id,
        tableNumber: body.table_number ?? body.table ?? null,
        customerName: body.customer_name ?? body.customerName ?? null,
        customerPhone: body.customer_phone ?? body.phone ?? null,
        customerLocation: body.customer_location ?? body.location ?? null,
        items: body.items,
        notes: body.notes ?? null,
        idempotencyKey,
      })
      // Realtime event is published asynchronously via the transactional outbox
      // (inserted inside createOrderAtomic) — not here.
      return res.status(201).json(order)
    } catch (err) {
      console.error('[orders POST] Error:', err.message)
      if (err.code === 'IDEMPOTENCY_KEY_REQUIRED') return res.status(400).json({ error: err.message, code: err.code })
      if (err.code === 'IDEMPOTENCY_CONFLICT') return res.status(409).json({ error: err.message, code: err.code })
      if (err.code === 'VALIDATION') return res.status(400).json({ error: err.message, code: err.code })
      if (err.code === 'INVALID_ITEM' || err.code === 'INVALID_OPTION') return res.status(422).json({ error: err.message, code: err.code })
      if (err.code === 'DUPLICATE') return res.status(409).json({ error: err.message, code: err.code })
      return res.status(500).json({ error: err.message })
    }
  }

  try {
    // ── POST updateStatus — requires MANAGEMENT_ROLES membership ─────────────────
    if (action === 'updateStatus') {
      const { orderId, status } = req.body
      if (!orderId || !status) return res.status(400).json({ error: 'orderId and status required' })

      // Resolve restaurantId from DB — never trust caller-supplied restaurantId.
      // A member of restaurant A could otherwise change an order belonging to restaurant B.
      const resolvedRestaurantId = await getNeonOrderRestaurantId(orderId)
      if (!resolvedRestaurantId) return res.status(404).json({ error: 'Order not found' })

      const access = await checkRestaurantAccess(req, resolvedRestaurantId)
      if (access.error === 'Not authenticated') return res.status(401).json({ error: 'Not authenticated' })
      if (!access.allowed) return res.status(403).json({ error: 'Access denied' })
      if (!access.isSuperadmin && !MANAGEMENT_ROLES.includes(access.role)) {
        return res.status(403).json({ error: 'Updating order status requires manager role or above' })
      }

      const ip = getClientIp(req)
      const { allowed } = await rateLimit(`rl:order-status:ip:${ip}`, 60, 60)
      if (!allowed) return send429(res, 'Too many order status updates.')
      const lockKey = `lock:order-status:${orderId}`
      const { acquired, token } = await acquireLock(lockKey, 5)
      if (!acquired) return res.status(409).json({ error: 'Status update already in progress.' })
      try {
        const updatedRow = await applyOrderStatusTransition(orderId, status)
        // Realtime event is published asynchronously via the transactional outbox
        // (inserted inside applyOrderStatusTransition) — not here.
        return res.json({ success: true, orderId, status, restaurant_id: updatedRow.restaurant_id })
      } catch (transitionErr) {
        if (transitionErr.code === 'TERMINAL' || transitionErr.code === 'INVALID_TRANSITION') {
          return res.status(409).json({ error: transitionErr.message, code: transitionErr.code })
        }
        if (transitionErr.code === 'INVALID_STATUS') {
          return res.status(422).json({ error: transitionErr.message, code: transitionErr.code })
        }
        if (transitionErr.code === 'NOT_FOUND') {
          return res.status(404).json({ error: transitionErr.message, code: transitionErr.code })
        }
        throw transitionErr
      } finally { await releaseLock(lockKey, token) }
    }

    // ── POST autoCleanup — superadmin only ────────────────────────────────────────
    if (action === 'autoCleanup') {
      // requireSuperadmin is an Express middleware — call it manually for Vercel handlers
      const superadminResult = await new Promise((resolve) => {
        const fakeNext = () => resolve({ ok: true })
        const fakeRes = {
          _status: null, _body: null,
          status(s) { this._status = s; return this },
          json(b) { this._body = b; resolve({ ok: false, status: this._status, body: b }); return this },
        }
        requireSuperadmin(req, fakeRes, fakeNext)
      })
      if (!superadminResult.ok) {
        return res.status(superadminResult.status).json(superadminResult.body)
      }

      const { confirmedDeleteHours = 12, rejectedDeleteMinutes = 10 } = req.body || {}
      const now = Date.now()
      const deletedCount = await deleteOldNeonOrders(
        new Date(now - confirmedDeleteHours * 3600000).toISOString(),
        new Date(now - rejectedDeleteMinutes * 60000).toISOString()
      )
      return res.json({ success: true, deletedCount })
    }

    return res.status(400).json({ error: `Unknown action: ${action}` })
  } catch (err) {
    console.error(`[orders][${action}] Error:`, err.message)
    return res.status(500).json({ error: err.message })
  }
}
