import { setPublicCors } from './_lib/cors.js'
import { checkRestaurantAccess, requireSuperadmin, ALL_ROLES, MANAGEMENT_ROLES } from './_lib/authz.js'
import { rateLimit, acquireLock, releaseLock, getClientIp, send429 } from '../src/lib/upstash.server.js'
import {
  deleteOldNeonOrders,
  getNeonOrdersPaginated,
  getNeonOrderRestaurantId,
} from '../src/db/neon-orders.js'
import { createOrderAtomic } from '../src/services/orderCreationService.js'
import { applyOrderStatusTransition } from '../src/services/orderStatusService.js'
import {
  generateRequestId,
  safeError,
  badInput,
  unauthorized,
  forbidden,
  notFound,
  conflict,
  internalError,
  rejectUnknownFields,
  validateUuid,
  validateString,
  validateEnum,
  parsePagination,
} from './_lib/validate.js'

const ALLOWED_CREATE_FIELDS = ['restaurant_id', 'items', 'table_number', 'table', 'customer_name', 'customerName', 'customer_phone', 'phone', 'customer_location', 'location', 'notes']

// ── /api/orders — Order Operations Handler (Neon-only) ───────────────────────
//
// GET  ?restaurantId=<id>    → list orders for restaurant [ALL_ROLES membership]
// POST (no action)          body: { restaurant_id, items, ... } → create order (public — customer flow)
// POST ?action=updateStatus body: { orderId, status } [MANAGEMENT_ROLES membership]
// POST ?action=autoCleanup  body: { confirmedDeleteHours?, rejectedDeleteMinutes? } [superadmin]
//
// Authorization is ALWAYS enforced — no environment-variable bypass.
// Order creation is server-authoritative: id, status, prices, totals, and
// timestamps are generated by createOrderAtomic, never trusted from the client.

export default async function handler(req, res) {
  setPublicCors(res)
  if (req.method === 'OPTIONS') return res.status(200).end()

  const requestId = generateRequestId()

  // ── GET: list orders for a restaurant — requires restaurant membership ──────
  if (req.method === 'GET') {
    const { restaurantId } = req.query
    if (!restaurantId) return badInput(res, 'restaurantId is required', requestId)

    const access = await checkRestaurantAccess(req, restaurantId)
    if (access.error === 'Not authenticated') return unauthorized(res, null, requestId)
    if (!access.allowed) return forbidden(res, null, requestId)
    if (!access.isSuperadmin && !ALL_ROLES.includes(access.role)) {
      return forbidden(res, null, requestId)
    }

    try {
      const pagination = parsePagination(req.query)
      const result = await getNeonOrdersPaginated(restaurantId, pagination)
      return res.status(200).json(result)
    } catch (err) {
      console.error('[orders GET] Error:', err.message)
      return internalError(res, requestId)
    }
  }

  if (req.method !== 'POST') return safeError(res, 405, 'Method not allowed', requestId)

  const action = req.query.action

  // ── POST (no action): create order — public customer flow ────────────────────
  if (!action) {
    const body = req.body
    const idempotencyKey = req.headers['idempotency-key']
    if (!idempotencyKey || typeof idempotencyKey !== 'string' || idempotencyKey.length < 16) {
      return badInput(res, 'Idempotency-Key header is required (min 16 characters).', requestId)
    }
    if (!body?.restaurant_id || !Array.isArray(body?.items) || body.items.length === 0) {
      return badInput(res, 'restaurant_id and a non-empty items array are required', requestId)
    }
    try {
      rejectUnknownFields(body, ALLOWED_CREATE_FIELDS)
      const order = await createOrderAtomic({
        restaurantId: body.restaurant_id,
        tableNumber: body.table_number ?? body.table ?? null,
        customerName: body.customer_name ?? body.customerName ?? null,
        customerPhone: body.customer_phone ?? body.phone ?? null,
        customerLocation: body.customer_location ?? body.location ?? null,
        items: body.items,
        notes: body.notes ?? null,
        idempotencyKey,
      })
      return res.status(201).json(order)
    } catch (err) {
      console.error('[orders POST] Error:', err.message)
      if (err.code === 'IDEMPOTENCY_KEY_REQUIRED') return badInput(res, err.message, requestId)
      if (err.code === 'IDEMPOTENCY_CONFLICT') return conflict(res, err.message, requestId)
      if (err.code === 'VALIDATION') return badInput(res, err.message, requestId)
      if (err.code === 'INVALID_ITEM' || err.code === 'INVALID_OPTION') return safeError(res, 422, err.message, requestId)
      if (err.code === 'DUPLICATE') return conflict(res, err.message, requestId)
      return internalError(res, requestId)
    }
  }

  try {
    // ── POST updateStatus — requires MANAGEMENT_ROLES membership ────────────────
    if (action === 'updateStatus') {
      const { orderId, status } = req.body
      if (!orderId || !status) return badInput(res, 'orderId and status required', requestId)
      rejectUnknownFields(req.body, ['orderId', 'status', 'restaurantId'])

      const resolvedRestaurantId = await getNeonOrderRestaurantId(orderId)
      if (!resolvedRestaurantId) return notFound(res, 'Order not found', requestId)

      const access = await checkRestaurantAccess(req, resolvedRestaurantId)
      if (access.error === 'Not authenticated') return unauthorized(res, null, requestId)
      if (!access.allowed) return forbidden(res, null, requestId)
      if (!access.isSuperadmin && !MANAGEMENT_ROLES.includes(access.role)) {
        return forbidden(res, 'Updating order status requires manager role or above', requestId)
      }

      const ip = getClientIp(req)
      const { allowed } = await rateLimit(`rl:order-status:ip:${ip}`, 60, 60)
      if (!allowed) return send429(res, 'Too many order status updates.')
      const lockKey = `lock:order-status:${orderId}`
      const { acquired, token } = await acquireLock(lockKey, 5)
      if (!acquired) return conflict(res, 'Status update already in progress.', requestId)
      try {
        const updatedRow = await applyOrderStatusTransition(orderId, status)
        return res.json({ success: true, orderId, status, restaurant_id: updatedRow.restaurant_id, requestId })
      } catch (transitionErr) {
        if (transitionErr.code === 'TERMINAL' || transitionErr.code === 'INVALID_TRANSITION') {
          return conflict(res, transitionErr.message, requestId)
        }
        if (transitionErr.code === 'INVALID_STATUS') {
          return safeError(res, 422, transitionErr.message, requestId)
        }
        if (transitionErr.code === 'NOT_FOUND') {
          return notFound(res, transitionErr.message, requestId)
        }
        throw transitionErr
      } finally { await releaseLock(lockKey, token) }
    }

    // ── POST autoCleanup — superadmin only ───────────────────────────────────
    if (action === 'autoCleanup') {
      const superadminResult = await new Promise((resolve) => {
        const fakeNext = () => resolve({ ok: true })
        const fakeRes = {
          _status: null, _body: null,
          status(s) { this._status = s; return this },
          json(b) { this._body = b; resolve({ ok: false, status: this._status, body: b }); return this },
        }
        requireSuperadmin(req, fakeRes, fakeNext)
      })
      if (!superadminResult.ok) {
        return res.status(superadminResult.status).json(superadminResult.body)
      }

      const { confirmedDeleteHours = 12, rejectedDeleteMinutes = 10 } = req.body || {}
      rejectUnknownFields(req.body || {}, ['confirmedDeleteHours', 'rejectedDeleteMinutes'])
      const now = Date.now()
      const deletedCount = await deleteOldNeonOrders(
        new Date(now - confirmedDeleteHours * 3600000).toISOString(),
        new Date(now - rejectedDeleteMinutes * 60000).toISOString()
      )
      return res.json({ success: true, deletedCount, requestId })
    }

    return badInput(res, `Unknown action: ${action}`, requestId)
  } catch (err) {
    console.error(`[orders][${action}] Error:`, err.message)
    return internalError(res, requestId)
  }
}
